name: Helm lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run Helm lint
        run: helm lint charts/too-restful-api 
