name: Helm lint

on: push

jobs:
  lint:
    uses: kube-the-home/github-actions/.github/workflows/helm-lint.yaml@962260b6048afd17325015c372eeb835a04b25b2 # v1.4.2
    with:
      chart_path: charts/too-restful-api
