name: Helm lint

on: push

jobs:
  lint:
    uses: kube-the-home/github-actions/.github/workflows/helm-lint.yaml@e698429ae3d6096c14d7eb6d2ffef1da8c26cdea # v1.4.1
    with:
      chart_path: charts/too-restful-api
