name: Helm lint

on: push

jobs:
  lint:
    uses: kube-the-home/github-actions/.github/workflows/helm-lint.yaml@7c879724555fc18be9f0d0a78b3c75283a95d406 # v1.2.1
    with:
      chart_path: charts/too-restful-api
