name: Conventional Commits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conventions:
    uses: kube-the-home/github-actions/.github/workflows/git-conventions.yaml@70b35bb255a89f5a9281934be8941da086031276 # v1.4.11
