name: Conventional Commits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conventions:
    uses: kube-the-home/github-actions/.github/workflows/git-conventions.yaml@7d8043b1d454e713b465c324c99d929a4a625a98 # v1.4.12
